### ISSUE TITLE
I cannot see where to access the data collected as part of the CEDS uPMU project

### ISSUE THREAD

**Issue by tmcdougalljr** [lbnl-cybersecurity/lbnl-cybersecurity.github.io#11]
At the risk of sounding incompetent I cannot see how to access the data collected during the CEDS uPMU project.   if you can poitn me in the right direction it would be appreciated.  Or let me know if this data is not publicly available.

**Comment by mansur007** [comment]
> At the risk of sounding incompetent I cannot see how to access the data collected during the CEDS uPMU project. if you can poitn me in the right direction it would be appreciated. Or let me know if this data is not publicly available.

same here, any updates?

**Comment by tmcdougalljr** [comment]
I reached out to the lab and found out that the data has been taken down.  That happened a few months ago.

**Comment by peisert** [comment]
I'm sorry, this data is no longer available.
