### ISSUE TITLE
microPMU Data Description

### ISSUE THREAD

**Issue by anelkawang** [lbnl-cybersecurity/lbnl-cybersecurity.github.io#3]
Hello,

I'm very interested with this great dataset. I'm wondering could you please provide more descriptions regarding the data. 

For data available at http://powerdata-download.lbl.gov/data/, with MATLAB functions, each csv is a 120000000 by 2 matrix. I can understand that the second column represents the the voltage or current magnitude/phase angles. Then, what is the first column stands for? If it is for the time clock, how should we interpret the recorded long strings?

From the LBNL Open Power Data v2.0, currently the data output is 2 samples per cycle, 120 points per second. Then there is 1e6 seconds covered, not as 3 month data claimed in the document. It would be really helpful if relevant information are shared. 

Thank you very much for the help!

**Comment by sanusaroj** [comment]
Hello,
Kindly tell me how did you obtain the data from the csv file.

**Comment by amoat7** [comment]
@anelkawang  yes, the data is not 3 months as claimed in the paper. It's only for 12 days. Did you find any other pmu data?
