### ISSUE TITLE
Micro PMU data from lbnl

### ISSUE THREAD

**Issue by zuhaib272** [lbnl-cybersecurity/lbnl-cybersecurity.github.io#6]
Hello Sir/Mam
I am a Research Scholar working on event detection and classification of different kinds of faults using Micro PMU data. I am using your lbnl micro PMU data set.I have the following  issues with the data set
1 How can we extract such a huge data set from Micro PMUs provided by lbnl in CSV format to extract an event?
2 Also, how can we plot any event from PMU data provided using Mr Plotter platform? There is no option to upload the data.
Kindly help me in this regard

Mohd Zuhaib
Research Scholar
EED,AMU

**Comment by sanusaroj** [comment]
Hello sir,
I am facing the same problem.Have you found any solution for the issues?
